version: '3'

services:

  eosio:
    # image: eosio/eos-dev
    image: eosio/eos
    container_name: eosio
    working_dir: /opt/work
    volumes:
      - ./bin:/root/bin
      - ./eosio-wallet:/root/eosio-wallet
      - ./work:/opt/work
    ports:
      - "8888:8888"
      - "9876:9876"
    command: ["nodeos",
          "-e",
          "-p",
          "eosio",
          "--plugin",
          "eosio::wallet_api_plugin",
          "--plugin",
          "eosio::wallet_plugin",
          "--plugin",
          "eosio::producer_plugin",
          "--plugin",
          "eosio::history_plugin",
          "--plugin",
          "eosio::chain_api_plugin",
          "--plugin",
          "eosio::history_api_plugin",
          "--plugin",
          "eosio::http_plugin",
          "--access-control-allow-origin", "*",
          "--contracts-console"
        ]
